apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - redis.yaml
  - java-app.yaml
  # - temp-prune-check.yaml   #prune excercise
  - db-migration-job.yaml #pre-sync excercise
