apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# patches:
#   - replicas-prod-patch.yaml
patches:
- target:
    kind: Deployment
    name: app1
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2