apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop-dev

resources:
  - ../../base

# Obraz aplikacji opublikowany w GitHub Container Registry
images:
  - name: shop-backend
    newName: ghcr.io/pchmielecki87/shop-backend
    newTag: dev

# Zwiększenie liczby replik na środowisku DEV
patches:
  - target:
      kind: Deployment
      name: shop-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
